---
title: "Pay Transparency"
author: "All of us"
date: "4/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# list of necessary packages
pkgs <- c('tidyverse','ggplot2','googlesheets4','devtools')

# if necessary packages aren't already installed, install them
new.pkgs <- pkgs[!(pkgs %in% installed.packages()[,"Package"])]
if(length(new.pkgs) > 0) install.packages(new.pkgs)
library(tidyverse,ggplot2)

# install.packages("devtools")
devtools::install_github("tidyverse/googlesheets4")

library(googlesheets4)
gs4_auth(email="maxmacalla.maps@gmail.com")

pay_responses <- read_sheet("https://docs.google.com/spreadsheets/d/1oxZDVMxWXUf_CWYazcu-HcwyblLxXWh3a7Zvz9BtA34/edit#gid=1324672452")

pay_responses$title <- factor(pay_responses$title, 
                              levels = c('Senior Technician',
                                         'Analyst',
                                         'Senior Analyst',
                                         'Lead Analyst',
                                         'Technical Specialist'))

pay_responses$newgender <- pay_responses$gender
pay_responses$newgender <- ifelse(pay_responses$newgender == 'Man','Men','Women/Other')
```

## Pay distribution by role


```{r pay, echo=FALSE}
payoverall <- ggplot(pay_responses, aes(x=title,y=hourly)) +
  geom_boxplot() + labs(x="",y="Hourly Pay ($)")
payoverall

paybygender <- ggplot(pay_responses, aes(x=title, y=hourly, color=newgender)) +
  geom_boxplot() + labs(x="", y="Hourly Pay ($)", color="")
paybygender
```

